apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - env:
        - name: MARIADB_DATABASE
          value: bugs
        - name: MARIADB_PASSWORD
          value: bugs
        - name: MARIADB_USER
          value: bugs
        image: bitnami/mariadb:latest
        name: mariadb
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: mariadb-data
      restartPolicy: Always
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
status: {}
