apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bugzilla
  name: bugzilla
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bugzilla
    spec:
      containers:
      - image: jwiegley/bugzilla
        name: bugzilla
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /home/bugzilla
          name: bugzilla-data
      restartPolicy: Always
      volumes:
      - name: bugzilla-data
        persistentVolumeClaim:
          claimName: bugzilla-data
status: {}
